name: Build
on:
  push:
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        uses: threeal/cmake-action@v1.3.0
        with:
          source-dir: .
          build-dir: build
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++

      - name: Build
        shell: bash
        run: cd build && ninja

      - name: Test
        shell: bash
        run: ctest --test-dir build
